### PR TITLE
[ENHANCEMENT-4] Added updated slide deck and models

### PR DESCRIPTION
**Pull request by mrinoybanerjee**
Hi team,

Title: PR: Added updated slide deck and models

Description:

- The slide deck has been updated to include objective, motivation, model metric comparison, and non-deep learning model.
- The dataset has been added as a zipped file.
- Trained models are now included in the Models folder.

Thank you

### CODE REVIEW

**Review by rootsec1 — APPROVED** [review]
Slides look great, only the shift to EfficientNet in the code is pending

**Review by rootsec1 — APPROVED** [review]
Added the WoundDataset.zip file in the `data/raw` folder

**Comment by pallesaisamyukta** [comment]
Thank you Abhishek for adding the data file!

**Comment by mrinoybanerjee** [comment]
Looks awesome guys! Thank you for the add-ons! This looks good to be shipped.

**Pull request merged**
